/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiser_jnidemo_jni_JniUtil */

#ifndef _Included_com_wiser_jnidemo_jni_JniUtil
#define _Included_com_wiser_jnidemo_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiser_jnidemo_jni_JniUtil
 * Method:    textStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wiser_jnidemo_jni_JniUtil_textStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
